      SUBROUTINE EXTRASEND()
      USE SIZES,        ONLY: ISIZE
      USE PROCM_INT, ONLY: NEWIND=>PNEWIF                                       
      USE NMBAYES_INT, ONLY: BAYES_EXTRA,THINPRINT
      USE PNM_CONFIG, ONLY: PNM_RUN_MODE,PNM_MANAGER,PNM_WORKER,PNM_SINGLE,PNM_WORKER_COUNT,PNM_MPI_NODE,PNM_OFF
      IMPLICIT NONE
      INTEGER IBUFF(10),I,J
      IF(PNM_RUN_MODE==PNM_SINGLE) RETURN
      IF(NEWIND/=0) RETURN
      IF(PNM_RUN_MODE==PNM_MANAGER) THEN
        IBUFF(1)=BAYES_EXTRA
        IBUFF(2)=THINPRINT
        J=0
        DO I=1, PNM_WORKER_COUNT  ! For each worker dir...
          IF (PNM_OFF(I+1) == 1) CYCLE
          J=J+1
          PNM_MPI_NODE=J
          CALL PNM_MPI_SEND(IBUFF,2)
        ENDDO
      ELSE
        CALL PNM_MPI_RECV(IBUFF,2)
        BAYES_EXTRA=IBUFF(1)
        THINPRINT=IBUFF(2)
      ENDIF
      RETURN
      END
      